name: AxAFKZone
version: '${project.version}'
main: com.artillexstudios.axafkzone.AxAFKZone
api-version: '1.20'
folia-supported: true
softdepend: [ProtocolLib]

permissions:
  axafkzone.admin:
    default: op